### ISSUE TITLE
eslint-like extend feature

### ISSUE THREAD

**Issue by ghaschel** [htmlhint/vscode-htmlhint#68]
Is there such a thing available in this package? There was an old issue in the original htmlhint repository but it never got to be merged.

I have some settings I want to share between repositories and tbh, replicating a lot of times is not very maintainable, so this is imho a very desirable feature

**Comment by coliff** [comment]
heya - I think this is a feature request that belongs in the HTMLHint repo rather than the VS Code extension. If such a feature was ever added it'd be done in the main HTMLHint rather than this extension.

Can you take a look over there and see if you can find that issue and give it a bump / or a +1 ?
